on:
  push:
    paths:
      - '**'
      - '!**/*.md'
      - '!**/*.http'
      - '!.vscode/**'
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: py-with-poetry
  DEPLOY_PATH: './infra'
  PYTHON_VERSION: '3.11'

name: Build and deploy
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd '.'
          python -m pip install --upgrade pip
          pip install poetry
          poetry export --without-hashes --format=requirements.txt > requirements.txt
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Zip artifact for deployment
        working-directory: ${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}
        run: zip -r release.zip . -x infra/**\*

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: release.zip
